/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReservaRouteImport } from './routes/reserva'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppFavoritosRouteImport } from './routes/app/favoritos'
import { Route as AppNotificacoesRouteImport } from './routes/app/notificacoes'
import { Route as AppPagamentosRouteImport } from './routes/app/pagamentos'
import { Route as AppPerfilRouteImport } from './routes/app/perfil'
import { Route as AppReservasRouteImport } from './routes/app/reservas'
import { Route as AppTimeRouteImport } from './routes/app/time'
import { Route as ArenaArenaIdRouteImport } from './routes/arena.$arenaId'
import { Route as ProprietarioIndexRouteImport } from './routes/proprietario/index'
import { Route as ProprietarioAgendaRouteImport } from './routes/proprietario/agenda'
import { Route as ProprietarioAreninhaRouteImport } from './routes/proprietario/areninha'
import { Route as ProprietarioAvaliacoesRouteImport } from './routes/proprietario/avaliacoes'
import { Route as ProprietarioCadastrarRouteImport } from './routes/proprietario/cadastrar'
import { Route as ProprietarioCamposRouteImport } from './routes/proprietario/campos'
import { Route as ProprietarioClientesRouteImport } from './routes/proprietario/clientes'
import { Route as ProprietarioConfiguracoesRouteImport } from './routes/proprietario/configuracoes'
import { Route as ProprietarioFinanceiroRouteImport } from './routes/proprietario/financeiro'
import { Route as ProprietarioNotificacoesRouteImport } from './routes/proprietario/notificacoes'
import { Route as ProprietarioPromocoesRouteImport } from './routes/proprietario/promocoes'
import { Route as ProprietarioRelatoriosRouteImport } from './routes/proprietario/relatorios'
import { Route as ProprietarioReservasRouteImport } from './routes/proprietario/reservas'
import { Route as ProprietarioTimesRouteImport } from './routes/proprietario/times'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaRoute = ReservaRouteImport.update({
  id: '/reserva',
  path: '/reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFavoritosRoute = AppFavoritosRouteImport.update({
  id: '/app/favoritos',
  path: '/app/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/app/notificacoes',
  path: '/app/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPagamentosRoute = AppPagamentosRouteImport.update({
  id: '/app/pagamentos',
  path: '/app/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/app/perfil',
  path: '/app/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReservasRoute = AppReservasRouteImport.update({
  id: '/app/reservas',
  path: '/app/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimeRoute = AppTimeRouteImport.update({
  id: '/app/time',
  path: '/app/time',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaArenaIdRoute = ArenaArenaIdRouteImport.update({
  id: '/arena/$arenaId',
  path: '/arena/$arenaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioIndexRoute = ProprietarioIndexRouteImport.update({
  id: '/proprietario/',
  path: '/proprietario/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioAgendaRoute = ProprietarioAgendaRouteImport.update({
  id: '/proprietario/agenda',
  path: '/proprietario/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioAreninhaRoute = ProprietarioAreninhaRouteImport.update({
  id: '/proprietario/areninha',
  path: '/proprietario/areninha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioAvaliacoesRoute = ProprietarioAvaliacoesRouteImport.update({
  id: '/proprietario/avaliacoes',
  path: '/proprietario/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioCadastrarRoute = ProprietarioCadastrarRouteImport.update({
  id: '/proprietario/cadastrar',
  path: '/proprietario/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioCamposRoute = ProprietarioCamposRouteImport.update({
  id: '/proprietario/campos',
  path: '/proprietario/campos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioClientesRoute = ProprietarioClientesRouteImport.update({
  id: '/proprietario/clientes',
  path: '/proprietario/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioConfiguracoesRoute =
  ProprietarioConfiguracoesRouteImport.update({
    id: '/proprietario/configuracoes',
    path: '/proprietario/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProprietarioFinanceiroRoute = ProprietarioFinanceiroRouteImport.update({
  id: '/proprietario/financeiro',
  path: '/proprietario/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioNotificacoesRoute =
  ProprietarioNotificacoesRouteImport.update({
    id: '/proprietario/notificacoes',
    path: '/proprietario/notificacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProprietarioPromocoesRoute = ProprietarioPromocoesRouteImport.update({
  id: '/proprietario/promocoes',
  path: '/proprietario/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioRelatoriosRoute = ProprietarioRelatoriosRouteImport.update({
  id: '/proprietario/relatorios',
  path: '/proprietario/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioReservasRoute = ProprietarioReservasRouteImport.update({
  id: '/proprietario/reservas',
  path: '/proprietario/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioTimesRoute = ProprietarioTimesRouteImport.update({
  id: '/proprietario/times',
  path: '/proprietario/times',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/login': typeof LoginRoute
  '/reserva': typeof ReservaRoute
  '/app/favoritos': typeof AppFavoritosRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/reservas': typeof AppReservasRoute
  '/app/time': typeof AppTimeRoute
  '/arena/$arenaId': typeof ArenaArenaIdRoute
  '/proprietario/agenda': typeof ProprietarioAgendaRoute
  '/proprietario/areninha': typeof ProprietarioAreninhaRoute
  '/proprietario/avaliacoes': typeof ProprietarioAvaliacoesRoute
  '/proprietario/cadastrar': typeof ProprietarioCadastrarRoute
  '/proprietario/campos': typeof ProprietarioCamposRoute
  '/proprietario/clientes': typeof ProprietarioClientesRoute
  '/proprietario/configuracoes': typeof ProprietarioConfiguracoesRoute
  '/proprietario/financeiro': typeof ProprietarioFinanceiroRoute
  '/proprietario/notificacoes': typeof ProprietarioNotificacoesRoute
  '/proprietario/promocoes': typeof ProprietarioPromocoesRoute
  '/proprietario/relatorios': typeof ProprietarioRelatoriosRoute
  '/proprietario/reservas': typeof ProprietarioReservasRoute
  '/proprietario/times': typeof ProprietarioTimesRoute
  '/app/': typeof AppIndexRoute
  '/proprietario/': typeof ProprietarioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/login': typeof LoginRoute
  '/reserva': typeof ReservaRoute
  '/app/favoritos': typeof AppFavoritosRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/reservas': typeof AppReservasRoute
  '/app/time': typeof AppTimeRoute
  '/arena/$arenaId': typeof ArenaArenaIdRoute
  '/proprietario/agenda': typeof ProprietarioAgendaRoute
  '/proprietario/areninha': typeof ProprietarioAreninhaRoute
  '/proprietario/avaliacoes': typeof ProprietarioAvaliacoesRoute
  '/proprietario/cadastrar': typeof ProprietarioCadastrarRoute
  '/proprietario/campos': typeof ProprietarioCamposRoute
  '/proprietario/clientes': typeof ProprietarioClientesRoute
  '/proprietario/configuracoes': typeof ProprietarioConfiguracoesRoute
  '/proprietario/financeiro': typeof ProprietarioFinanceiroRoute
  '/proprietario/notificacoes': typeof ProprietarioNotificacoesRoute
  '/proprietario/promocoes': typeof ProprietarioPromocoesRoute
  '/proprietario/relatorios': typeof ProprietarioRelatoriosRoute
  '/proprietario/reservas': typeof ProprietarioReservasRoute
  '/proprietario/times': typeof ProprietarioTimesRoute
  '/app': typeof AppIndexRoute
  '/proprietario': typeof ProprietarioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/login': typeof LoginRoute
  '/reserva': typeof ReservaRoute
  '/app/favoritos': typeof AppFavoritosRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/reservas': typeof AppReservasRoute
  '/app/time': typeof AppTimeRoute
  '/arena/$arenaId': typeof ArenaArenaIdRoute
  '/proprietario/agenda': typeof ProprietarioAgendaRoute
  '/proprietario/areninha': typeof ProprietarioAreninhaRoute
  '/proprietario/avaliacoes': typeof ProprietarioAvaliacoesRoute
  '/proprietario/cadastrar': typeof ProprietarioCadastrarRoute
  '/proprietario/campos': typeof ProprietarioCamposRoute
  '/proprietario/clientes': typeof ProprietarioClientesRoute
  '/proprietario/configuracoes': typeof ProprietarioConfiguracoesRoute
  '/proprietario/financeiro': typeof ProprietarioFinanceiroRoute
  '/proprietario/notificacoes': typeof ProprietarioNotificacoesRoute
  '/proprietario/promocoes': typeof ProprietarioPromocoesRoute
  '/proprietario/relatorios': typeof ProprietarioRelatoriosRoute
  '/proprietario/reservas': typeof ProprietarioReservasRoute
  '/proprietario/times': typeof ProprietarioTimesRoute
  '/app/': typeof AppIndexRoute
  '/proprietario/': typeof ProprietarioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/login'
    | '/reserva'
    | '/app/favoritos'
    | '/app/notificacoes'
    | '/app/pagamentos'
    | '/app/perfil'
    | '/app/reservas'
    | '/app/time'
    | '/arena/$arenaId'
    | '/proprietario/agenda'
    | '/proprietario/areninha'
    | '/proprietario/avaliacoes'
    | '/proprietario/cadastrar'
    | '/proprietario/campos'
    | '/proprietario/clientes'
    | '/proprietario/configuracoes'
    | '/proprietario/financeiro'
    | '/proprietario/notificacoes'
    | '/proprietario/promocoes'
    | '/proprietario/relatorios'
    | '/proprietario/reservas'
    | '/proprietario/times'
    | '/app/'
    | '/proprietario/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/login'
    | '/reserva'
    | '/app/favoritos'
    | '/app/notificacoes'
    | '/app/pagamentos'
    | '/app/perfil'
    | '/app/reservas'
    | '/app/time'
    | '/arena/$arenaId'
    | '/proprietario/agenda'
    | '/proprietario/areninha'
    | '/proprietario/avaliacoes'
    | '/proprietario/cadastrar'
    | '/proprietario/campos'
    | '/proprietario/clientes'
    | '/proprietario/configuracoes'
    | '/proprietario/financeiro'
    | '/proprietario/notificacoes'
    | '/proprietario/promocoes'
    | '/proprietario/relatorios'
    | '/proprietario/reservas'
    | '/proprietario/times'
    | '/app'
    | '/proprietario'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/login'
    | '/reserva'
    | '/app/favoritos'
    | '/app/notificacoes'
    | '/app/pagamentos'
    | '/app/perfil'
    | '/app/reservas'
    | '/app/time'
    | '/arena/$arenaId'
    | '/proprietario/agenda'
    | '/proprietario/areninha'
    | '/proprietario/avaliacoes'
    | '/proprietario/cadastrar'
    | '/proprietario/campos'
    | '/proprietario/clientes'
    | '/proprietario/configuracoes'
    | '/proprietario/financeiro'
    | '/proprietario/notificacoes'
    | '/proprietario/promocoes'
    | '/proprietario/relatorios'
    | '/proprietario/reservas'
    | '/proprietario/times'
    | '/app/'
    | '/proprietario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  LoginRoute: typeof LoginRoute
  ReservaRoute: typeof ReservaRoute
  AppFavoritosRoute: typeof AppFavoritosRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPagamentosRoute: typeof AppPagamentosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppReservasRoute: typeof AppReservasRoute
  AppTimeRoute: typeof AppTimeRoute
  ArenaArenaIdRoute: typeof ArenaArenaIdRoute
  ProprietarioAgendaRoute: typeof ProprietarioAgendaRoute
  ProprietarioAreninhaRoute: typeof ProprietarioAreninhaRoute
  ProprietarioAvaliacoesRoute: typeof ProprietarioAvaliacoesRoute
  ProprietarioCadastrarRoute: typeof ProprietarioCadastrarRoute
  ProprietarioCamposRoute: typeof ProprietarioCamposRoute
  ProprietarioClientesRoute: typeof ProprietarioClientesRoute
  ProprietarioConfiguracoesRoute: typeof ProprietarioConfiguracoesRoute
  ProprietarioFinanceiroRoute: typeof ProprietarioFinanceiroRoute
  ProprietarioNotificacoesRoute: typeof ProprietarioNotificacoesRoute
  ProprietarioPromocoesRoute: typeof ProprietarioPromocoesRoute
  ProprietarioRelatoriosRoute: typeof ProprietarioRelatoriosRoute
  ProprietarioReservasRoute: typeof ProprietarioReservasRoute
  ProprietarioTimesRoute: typeof ProprietarioTimesRoute
  AppIndexRoute: typeof AppIndexRoute
  ProprietarioIndexRoute: typeof ProprietarioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva': {
      id: '/reserva'
      path: '/reserva'
      fullPath: '/reserva'
      preLoaderRoute: typeof ReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/favoritos': {
      id: '/app/favoritos'
      path: '/app/favoritos'
      fullPath: '/app/favoritos'
      preLoaderRoute: typeof AppFavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/app/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pagamentos': {
      id: '/app/pagamentos'
      path: '/app/pagamentos'
      fullPath: '/app/pagamentos'
      preLoaderRoute: typeof AppPagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/app/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reservas': {
      id: '/app/reservas'
      path: '/app/reservas'
      fullPath: '/app/reservas'
      preLoaderRoute: typeof AppReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/time': {
      id: '/app/time'
      path: '/app/time'
      fullPath: '/app/time'
      preLoaderRoute: typeof AppTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/$arenaId': {
      id: '/arena/$arenaId'
      path: '/arena/$arenaId'
      fullPath: '/arena/$arenaId'
      preLoaderRoute: typeof ArenaArenaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/': {
      id: '/proprietario/'
      path: '/proprietario'
      fullPath: '/proprietario/'
      preLoaderRoute: typeof ProprietarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/agenda': {
      id: '/proprietario/agenda'
      path: '/proprietario/agenda'
      fullPath: '/proprietario/agenda'
      preLoaderRoute: typeof ProprietarioAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/areninha': {
      id: '/proprietario/areninha'
      path: '/proprietario/areninha'
      fullPath: '/proprietario/areninha'
      preLoaderRoute: typeof ProprietarioAreninhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/avaliacoes': {
      id: '/proprietario/avaliacoes'
      path: '/proprietario/avaliacoes'
      fullPath: '/proprietario/avaliacoes'
      preLoaderRoute: typeof ProprietarioAvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/cadastrar': {
      id: '/proprietario/cadastrar'
      path: '/proprietario/cadastrar'
      fullPath: '/proprietario/cadastrar'
      preLoaderRoute: typeof ProprietarioCadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/campos': {
      id: '/proprietario/campos'
      path: '/proprietario/campos'
      fullPath: '/proprietario/campos'
      preLoaderRoute: typeof ProprietarioCamposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/clientes': {
      id: '/proprietario/clientes'
      path: '/proprietario/clientes'
      fullPath: '/proprietario/clientes'
      preLoaderRoute: typeof ProprietarioClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/configuracoes': {
      id: '/proprietario/configuracoes'
      path: '/proprietario/configuracoes'
      fullPath: '/proprietario/configuracoes'
      preLoaderRoute: typeof ProprietarioConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/financeiro': {
      id: '/proprietario/financeiro'
      path: '/proprietario/financeiro'
      fullPath: '/proprietario/financeiro'
      preLoaderRoute: typeof ProprietarioFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/notificacoes': {
      id: '/proprietario/notificacoes'
      path: '/proprietario/notificacoes'
      fullPath: '/proprietario/notificacoes'
      preLoaderRoute: typeof ProprietarioNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/promocoes': {
      id: '/proprietario/promocoes'
      path: '/proprietario/promocoes'
      fullPath: '/proprietario/promocoes'
      preLoaderRoute: typeof ProprietarioPromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/relatorios': {
      id: '/proprietario/relatorios'
      path: '/proprietario/relatorios'
      fullPath: '/proprietario/relatorios'
      preLoaderRoute: typeof ProprietarioRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/reservas': {
      id: '/proprietario/reservas'
      path: '/proprietario/reservas'
      fullPath: '/proprietario/reservas'
      preLoaderRoute: typeof ProprietarioReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/times': {
      id: '/proprietario/times'
      path: '/proprietario/times'
      fullPath: '/proprietario/times'
      preLoaderRoute: typeof ProprietarioTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  LoginRoute: LoginRoute,
  ReservaRoute: ReservaRoute,
  AppFavoritosRoute: AppFavoritosRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPagamentosRoute: AppPagamentosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppReservasRoute: AppReservasRoute,
  AppTimeRoute: AppTimeRoute,
  ArenaArenaIdRoute: ArenaArenaIdRoute,
  ProprietarioAgendaRoute: ProprietarioAgendaRoute,
  ProprietarioAreninhaRoute: ProprietarioAreninhaRoute,
  ProprietarioAvaliacoesRoute: ProprietarioAvaliacoesRoute,
  ProprietarioCadastrarRoute: ProprietarioCadastrarRoute,
  ProprietarioCamposRoute: ProprietarioCamposRoute,
  ProprietarioClientesRoute: ProprietarioClientesRoute,
  ProprietarioConfiguracoesRoute: ProprietarioConfiguracoesRoute,
  ProprietarioFinanceiroRoute: ProprietarioFinanceiroRoute,
  ProprietarioNotificacoesRoute: ProprietarioNotificacoesRoute,
  ProprietarioPromocoesRoute: ProprietarioPromocoesRoute,
  ProprietarioRelatoriosRoute: ProprietarioRelatoriosRoute,
  ProprietarioReservasRoute: ProprietarioReservasRoute,
  ProprietarioTimesRoute: ProprietarioTimesRoute,
  AppIndexRoute: AppIndexRoute,
  ProprietarioIndexRoute: ProprietarioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
